webmd-health-services/Whiskey

- Test/Invoke-WhiskeyNodeTask.Tests.ps1
- Test/Invoke-WhiskeyPublishNodeModuleTask.Tests.ps1
- Test/New-WhiskeyContext.Tests.ps1
- Test/WhiskeyTest.psm1
- Whiskey/Functions/Invoke-WhiskeyNodeTask.ps1
- Whiskey/Functions/Invoke-WhiskeyPublishNodeModuleTask.ps1
- Whiskey/Functions/New-WhiskeyContext.ps1
- build.ps1
- adding npmRegistryUri property 
- refactored WhiskeyNode Task test file
> Add npm registry uri property to node task

- Test/New-WhiskeyProGetUniversalPackage.Tests.ps1
- Whiskey/Functions/Invoke-WhiskeyRobocopy.ps1
> ProGetUniversalPackage task will no longer package empty directories

- Test/Publish-WhiskeyNodeModule.Tests.ps1
- Whiskey/Tasks/Publish-WhiskeyNodeModule.ps1
> Add error handling for npm publish command in PublishNodeModule task

- Test/Assemblies/NUnit3FailingTest/NUnit3FailingTest.csproj
- Test/Assemblies/NUnit3FailingTest/NUnit3FailingTest.sln
- Test/Assemblies/NUnit3FailingTest/Properties/AssemblyInfo.cs
- Test/Assemblies/NUnit3FailingTest/TestFixture.cs
- Test/Assemblies/NUnit3FailingTest/packages.config
- Test/Assemblies/NUnit3PassingTest/NUnit3PassingTest.csproj
- Test/Assemblies/NUnit3PassingTest/NUnit3PassingTest.sln
- Test/Assemblies/NUnit3PassingTest/Properties/AssemblyInfo.cs
- Test/Assemblies/NUnit3PassingTest/TestFixture.cs
- Test/Assemblies/NUnit3PassingTest/packages.config
- Test/Invoke-WhiskeyNUnit3Task.Tests.ps1
- Whiskey/Tasks/Invoke-WhiskeyNUnit3Task.ps1
> Added Invoke-WhiskeyNUnit3Task and tests

- Test/Invoke-WhiskeyNodeTask.Tests.ps1
- Test/Publish-WhiskeyNodeModule.Tests.ps1
- Whiskey/Functions/Invoke-WhiskeyNodeTask.ps1
- Whiskey/Tasks/Publish-WhiskeyNodeModule.ps1
- Whiskey/Whiskey.psd1
* 'npm prune' now occurs in the 'PublishNodeModule' task
* 'npm prune' will use the locally installed version of npm if it exists
> 'npm prune' now occurs in the 'PublishNodeModule' task

- Test/New-WhiskeyProGetUniversalPackage.Tests.ps1
- Whiskey/Tasks/New-WhiskeyProGetUniversalPackage.ps1
- Whiskey/Whiskey.psd1
> Bug Fix: ProGet package fails when packaging only third party paths

- Test/New-WhiskeyProGetUniversalPackage.Tests.ps1
- Test/Publish-WhiskeyProGetUniversalPackage.Tests.ps1
- Test/Resolve-WhiskeyVariable.Tests.ps1
- Whiskey/Functions/New-WhiskeyContext.ps1
- Whiskey/Functions/New-WhiskeyVersionObject.ps1
- Whiskey/Functions/Resolve-WhiskeyVariable.ps1
- Whiskey/Tasks/New-WhiskeyProGetUniversalPackage.ps1
- Whiskey/Tasks/Publish-WhiskeyProGetUniversalPackage.ps1
- Whiskey/Whiskey.psd1
Need the ability to:
* Customize version of a ProGet package
* When publishing, overwrite a ProGet package if it exists
> ProGet Package Improvements

- Test/Invoke-WhiskeyNUnit2Task.Tests.ps1
- Test/Invoke-WhiskeyTask.Tests.ps1
- Test/New-WhiskeyProGetUniversalPackage.Tests.ps1
- Test/Resolve-WhiskeyVariable.Tests.ps1
- Test/Set-WhiskeyVariable.Tests.ps1
- Whiskey/Functions/Add-WhiskeyVariable.ps1
- Whiskey/Functions/Invoke-WhiskeyTask.ps1
- Whiskey/Functions/New-WhiskeyContextObject.ps1
- Whiskey/Tasks/Invoke-WhiskeyNUnit2Task.ps1
- Whiskey/Tasks/New-WhiskeyProGetUniversalPackage.ps1
- Whiskey/Whiskey.psd1
* Merged master into develop
* Updated Whiskey version to 0.24.0 and updated release notes
> Merge master to develop

- Test/Invoke-WhiskeyExec.Tests.ps1
- Test/Invoke-WhiskeyPipeline.Tests.ps1
- Test/New-WhiskeySemanticVersion.Tests.ps1
- Whiskey/Functions/Invoke-WhiskeyPipeline.ps1
- Whiskey/Tasks/Invoke-WhiskeyExec.ps1
- Whiskey/Whiskey.psd1
..to define executable path and arguments.
> Updated `Exec` task to support a single-line syntax..

- Test/New-WhiskeyProGetUniversalPackage.Tests.ps1
- Test/Resolve-WhiskeyVariable.Tests.ps1
- Whiskey/Functions/Resolve-WhiskeyVariable.ps1
- Whiskey/Whiskey.psd1
- Whiskey/en-US/about_Whiskey_Variables.help.txt
* Added a couple of new Whiskey variables.
* Added the ability to call methods/properties on Whiskey variable objects.
> Semver metadata variables

- Test/GitHubRelease.Tests.ps1
- Test/New-WhiskeyProGetUniversalPackage.Tests.ps1
- Whiskey/Functions/Resolve-WhiskeyTaskPath.ps1
- Whiskey/Functions/Stop-WhiskeyTask.ps1
- Whiskey/Tasks/New-WhiskeyGitHubRelease.ps1
- Whiskey/Tasks/Set-WhiskeyVariableFromPowerShellDataFile.ps1
- Whiskey/Whiskey.psd1
- Whiskey/en-US/about_Whiskey_GitHubRelease_Task.help.txt
- Whiskey/en-US/about_Whiskey_Tasks.help.txt
- build.ps1
- whiskey.yml
I've created a task that creates a release in GitHub. Very useful for all our open-source projects.
> GitHubRelease Task

- Test/Invoke-WhiskeyDotNetTest.Tests.ps1
- Whiskey/Tasks/Invoke-WhiskeyDotNetTest.ps1
- Whiskey/Whiskey.psd1
- Whiskey/en-US/about_Whiskey_DotNetTest_Task.help.txt
- Whiskey/en-US/about_Whiskey_Tasks.help.txt
Created `DotNetTest` task for running `dotnet test` on .NET Core test projects.
> Created DotNetTest task

- Whiskey/Whiskey.psd1
- Minor feature enchancement (adding NUnit2 support to NUnit3 task)
> PFORM-36: bump version to 0.42.0

- Test/build.ps1.Tests.ps1
- Whiskey/Whiskey.psd1
- Whiskey/build.ps1
- Whiskey/en-US/about_Whiskey.help.txt
- whiskey.yml
> Bootstrap Whiskey

- Test/PublishNodeModule.Tests.ps1
- Whiskey/Tasks/PublishNodeModule.ps1
- Whiskey/Whiskey.psd1
`PublishNodeModule` task now supports publishing prerelease versions of node modules.
> PublishNodeModule prerelease support

- Test/AppVeyorWaitForBuildJobs.Tests.ps1
- Whiskey/Tasks/AppVeyorWaitForBuildJobs.ps1
- Whiskey/Whiskey.psd1
- appveyor.yml
- build.ps1
- whiskey.yml
Created a task that does its best to wait for other jobs in a build to complete before continuing to the next build task. There are limitations because AppVeyor's API only returns information for the most recently started builds, but this is better than nothing.
> I'd like to be able to publish while running builds in parallel.

- Test/PowerShell.Tests.ps1
- Whiskey/Tasks/PowerShell.ps1
- Whiskey/Whiskey.psd1
Added a `ScriptBlock` property to the `PowerShell` task for defining a block of PowerShell code in the `whiskey.yml` for the task to run.
> Add ScriptBlock property to PowerShell task

- Test/ProGetUniversalPackage.Tests.ps1
- Whiskey/Tasks/ProGetUniversalPackage.ps1
- Whiskey/Tasks/PublishProGetAsset.ps1
- Whiskey/Tasks/PublishProGetUniversalPackage.ps1
- Whiskey/Whiskey.psd1
> Update ProGetAutomation PowerShell module dependency

- Test/Install-WhiskeyNode.Tests.ps1
- Test/Parallel.Tests.ps1
- Whiskey/Tasks/NuGetPush.ps1
- Whiskey/Whiskey.psm1
- appveyor.yml
These tests fail intermittently. I think I fixed a couple of them and improved error handling for another so we can better diagnose why it fails.
> Fix flaky tests

- Test/Initialize-WhiskeyTest.ps1
- Test/Install-WhiskeyNode.Tests.ps1
- Test/Install-WhiskeyPowerShellModule.Tests.ps1
- Test/PublishBitbucketServerTag.Tests.ps1
- Test/PublishPowerShellModule.Tests.ps1
- Test/PublishPowerShellScript.Tests.ps1
- Test/Resolve-WhiskeyNuGetPackageVersion.Tests.ps1
- Test/WhiskeyTest.psm1
- Test/Zip.Tests.ps1
- Whiskey/Functions/Get-WhiskeyPSModule.ps1
- Whiskey/Functions/Publish-WhiskeyPSObject.ps1
- Whiskey/Functions/Register-WhiskeyPSModulePath.ps1
- Whiskey/Functions/Unregister-WhiskeyPSModulePath.ps1
- Whiskey/Tasks/Pester4.ps1
- Whiskey/Tasks/PublishBitbucketServerTag.ps1
- Whiskey/Tasks/PublishPowerShellModule.ps1
- Whiskey/Tasks/PublishPowerShellScript.ps1
- Whiskey/Tasks/Zip.ps1
- Whiskey/Whiskey.psd1
Adding a task to publish powershell scripts.
> Adding PublishPowerShellScript Task
